### ISSUE TITLE
Option to set the solution's platform

### ISSUE THREAD

**Issue by salchint** [sterin/vscode-msbuild-tools#6]
I miss an option to define the platform when invoking *msbuild*.
In detail, an additional command line argument like `/p:Platform=Win32` is missing when invoking *msbuild* in order to successfully build my solutions.

**Comment by 0xsingularity** [comment]
I want to raise visibility on this feature request.  I'm currently just compiling my C++ project for Win32 and x64 (mainly to verify code correctness) but I plan to eventually target multiple other platforms.

This extension seems to work very well for the features it does implement, but being able to build for multiple platforms is critical.

**Comment by salchint** [comment]
I looks like @Estivoo has already implemented my missing feature in PR #7. Thx :)
